### PR TITLE
add the possibility to disable all quotes in a csv file

### PR DESCRIPTION
**Pull request by akeromnes**
remove all quotes of a csv file if needed.

### CODE REVIEW

**Comment by amanteaux** [comment]
Thank you for your contribution!

In your change you are using the method `CSVWriter.(nextLine, applyQuotesToAll)`. So actually, if you set the `applyQuotesToAll` to `false`, that does not mean that the CSV file won't contain any quote, it means that if a value does not contain any special characters (quote, escape, separator, newline, or return), then this value will not be wrapped with quotes.
Is that the intended behavior of your pull request?

**Comment by akeromnes** [comment]
Yes it's exactly that, disable wrapping quotes.

**Comment by amanteaux** [comment]
Just to be really sure of the behavior you implemented:
- the value `123` will be rendered with `123`: so no quotes
- the value `123,2` will be rendered with `"123,2"`: so quotes are displayed since they are mandatory in this case

Is this ok?

**Comment by akeromnes** [comment]
Yes this is the intended behavior.

**Pull request merged**
